### ISSUE TITLE
Not attempting to login via config credentials

### ISSUE THREAD

**Issue by dcrdev** [parlt/Roundcube-Plugin-Virtual-User-Mapping#1]
Is this a fully finished plugin?

I've attempted to configure this, but it always results in an unsuccessful login - as far as I can tell the plugin, when enabled doesn't alter the login behavior in any way.

The logs just show that roundcube is attempting to login to imap via the credentials supplied at the time of login, instead of those supplied in the configuration.

**Comment by parlt** [comment]
I have it not been well documented, before and now updated the documentation on the github page.

The plugin is at the moment not finished, but usable.
Did you used a splitter "#"  in your login?
Please take a look at the updated using information. https://github.com/parlt/Roundcube-Plugin-Virtual-User-Mapping/blob/master/README.md

If it does'nt work for you with a splitter "#" - please give me feedback.
